### ISSUE TITLE
Recently added items feature

### ISSUE THREAD

**Issue by pmallory** [pmallory/Catalog#10]
display some recently added items on the home page
this entails adding a timestamp to the items table.

**Comment by walesmd** [comment]
I've added all items to the index page. Just need the query to be updated to include: reverse chrono order, a limit of X items (20?) and joining the category name to each item.

**Comment by walesmd** [comment]
I implemented this in a ghetto way (but in a way I am comfortable with for this exercise). I just sorted by Item ID DESC and put a limit of 20 on it.

I'm okay with this implementation if you all are.

**Comment by eduardomed** [comment]
Fine by me

**Comment by pmallory** [comment]
:+1:
