### ISSUE TITLE
Validating inputs

### ISSUE THREAD

**Issue by eduardomed** [pmallory/Catalog#5]
Basically for all places where a form is being handled (add_category(), add_item(), etc)

**Comment by eduardomed** [comment]
So far, I've included validation at:

/catalog/category/add --> validates that no existing categories are created (no duplicates allowed). 

/catalog/item/add --> categories already auto-populate with the select box, so there's no risk of inputing a non-existent category. We need to decide if we will allowed duplicate items: if not, then we can add validation for that. 

/catalog/<item_name>/edit -->  categories already auto-populate with the select box, so there's no risk of updating to a non-existent category.

What else should we consider? Otherwise, feel free to test and close.

**Comment by walesmd** [comment]
Probably want to test that item name, category name and item description all actually include content (length of string is not 0).

**Comment by eduardomed** [comment]
Good call, added: 

/catalog/category/add --> no empty string for 'category'

/catalog/item/add --> no empty string for 'title' and 'description'

/catalog/<item_name>/edit --> no empty string for 'title' and 'description'

Anything else? If not, feel free to test and close

**Comment by pmallory** [comment]
looks good
