### ISSUE TITLE
Make add and item forms use a select box to choose the category

### ISSUE THREAD

**Issue by pmallory** [pmallory/Catalog#7]
The select should have the name and id of the category (for the reasons Mike has)

**Comment by eduardomed** [comment]
@pmallory the categories are in. Can you verify it works on your side and close this ticket?

**Comment by walesmd** [comment]
Select boxes are in there. We can potentially decrease the number of queries required during item insertion if we update the template to use the category ID for these select boxes and then update the backend to just insert that integer as item.cat_id

Don't want to make this change myself as I'm not all that familiar with SQLAlchemy - maybe it expects to be passed in the complete category object (which I think is how we're currently accomplishing this, which requires an initial query to get the category).

**Comment by eduardomed** [comment]
Ok, I think see what you mean. Let me see if I can clean that up a bit, will keep you guys posted.

**Comment by eduardomed** [comment]
So far no luck. I keep getting a "Bad request. The browser (or proxy) sent a request that this server could not understand" message. Gonna dig in a bit more, but it may be that it expects the complete category object.

**Comment by walesmd** [comment]
I don't think we really need to worry about it - particularly since students are never even going to see this code. We just need to it be functional enough for screenshots/video.
