### ISSUE TITLE
Autofilling edit_item.html field

### ISSUE THREAD

**Issue by eduardomed** [pmallory/Catalog#8]
Should fill in 'title', 'description', and 'category' with the pulldown menu.

**Comment by eduardomed** [comment]
Autofilling for all three fields has been added. I added an item.html in the templates to be able to grab the variables to auto-fill. That is, if you are at '/catalog/Soccer/Jersey', and click on the 'Edit' link, it should take you to the edit page with the soccer jersey info already populated. 

Can you verify it works on your side and close this ticket?

**Comment by walesmd** [comment]
Confirmed this is working for title and description, 51b12efdd addresses selecting the correct category.
